globals().update([('D_HIGH', HIGH), ('D_LOW', LOW), ('D_INPUT', INPUT),
                  ('D_OUTPUT', OUTPUT), ('D_SERIAL', SERIAL),
                  ('D_DISPLAY', DISPLAY), ('D_LSBFIRST', LSBFIRST),
                  ('D_MSBFIRST', MSBFIRST), ('D_CHANGE', CHANGE),
                  ('D_FALLING', FALLING), ('D_RISING', RISING),
                  ('D_NOT_A_PIN', NOT_A_PIN), ('D_NOT_A_PORT', NOT_A_PORT),
                  ('D_PA', PA), ('D_PB', PB), ('D_PC', PC), ('D_PD', PD),
                  ('D_PE', PE), ('D_PF', PF), ('D_PG', PG), ('D_PH', PH),
                  ('D_PJ', PJ), ('D_PK', PK), ('D_PL', PL),
                  ('D_TIMER0A', TIMER0A), ('D_TIMER0B', TIMER0B),
                  ('D_TIMER1A', TIMER1A), ('D_TIMER1B', TIMER1B),
                  ('D_TIMER2', TIMER2), ('D_TIMER2A', TIMER2A),
                  ('D_TIMER2B', TIMER2B), ('D_TIMER3A', TIMER3A),
                  ('D_TIMER3B', TIMER3B), ('D_TIMER3C', TIMER3C),
                  ('D_TIMER4A', TIMER4A), ('D_TIMER4B', TIMER4B),
                  ('D_TIMER4C', TIMER4C), ('D_TIMER4D', TIMER4D),
                  ('D_TIMER5A', TIMER5A), ('D_TIMER5B', TIMER5B),
                  ('D_TIMER5C', TIMER5C)])
